### ISSUE TITLE
Wrong variant select in multi module different build type project

### ISSUE THREAD

**Issue by PhilippNowak96** [PandoraMedia/variant-helper-plugin#2]
First: Thank you for this plugin, I was looking for something like this for a long time! 🙂

I have have a small issue:

- The project uses multiple modules, multiple flavors (let's say A, B and C) and multiple build types (debug, release, test)
- Some library modules are not flavored and only contain `debug` and `release` build type
- The `app` module uses all three flavors and all three build types (so there are 9 different variants in total)
- Some modules also use the three flavors but only two build types (debug, release).

When I select flavor A for the app module and `test` as build type, I need to select `release` (because basically `test` is just a release version with some things on top) for the library modules and flavor `A` + `release` for the modules which use flavors but don't have the `test` build type.

So I set `release`, `aTest` and `aRelease` in the variant helper plugin. The result is everything is changed to `release` build variant, so the flavor selection works correctly but the `test` build type is not selected but `release` instead.

If you need more information or a test project just let me know.

**Comment by gtcompscientist** [comment]
A test project would be great to help with the debugging. I think I know where to look, but making sure I'm not hunting the wrong thing would be best.

**Comment by PhilippNowak96** [comment]
[https://gitlab.com/PhilippNowak/varianthelpertest](url)

Clone and open this project and try to set these variants:

![image](https://user-images.githubusercontent.com/10376534/103917992-88b6b780-510e-11eb-85fd-d76bee3c7b83.png)

The `app` module will be set to `firstRelease` too instead of `firstSystest` @gtcompscientist

**Comment by gtcompscientist** [comment]
https://github.com/PandoraMedia/variant-helper-plugin/pull/3

If you would like to test your main project against this PR, that would verify the fix before I publish.

**Comment by gtcompscientist** [comment]
[variant-helper-plugin-1.1.0.zip](https://github.com/PandoraMedia/variant-helper-plugin/files/5836286/variant-helper-plugin-1.1.0.zip)

For easier testing, unzip and import the variant-helper-plugin-1.0.0.jar to your IDE and let me know!

**Comment by PhilippNowak96** [comment]
Works perfectly, thank you! :)
