### ISSUE TITLE
Mark IntelliJ as compatible

### ISSUE THREAD

**Issue by matejdro** [PandoraMedia/variant-helper-plugin#4]
Currently plugin cannot be installed directly from the repository because it is marked as only being compatible with Android Studio.

But downloading plugin zip and installing it manually works perfectly in IntelliJ + Android plugin. 

Could you mark IntelliJ IDEA as compatible on the plugin repository?

**Comment by gtcompscientist** [comment]
There is a potential for a `NoSuchMethodError` in IntelliJ under certain circumstances, use at your own risk.
